version: "3.8"

services:
  #  Create a service named db.
  db-service:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "postgres_database"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      POSTGRES_USER: ${LOCAL_DWH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOCAL_DWH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOCAL_DWH_POSTGRES_DB}
    #   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - 5432:5432
    #   Restart the container if it fails.
    expose:
      - "5432"
    volumes:
      - spark-db_volume:/var/lib/postgresql/data
    networks:
      - spark-network

    restart: always
volumes:
  spark-db_volume:
      driver: local
networks:
    spark-network:
        driver: bridge
        name: spark-network

